name: CI Playwright

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Instalar navegadores Playwright
        run: npx playwright install --with-deps

      - name: Listar archivos de la carpeta a servir
        run: ls -l

      - name: Levantar servidor local
        run: npx http-server -p 5500 > server.log 2>&1 &

      - name: Ver procesos activos
        run: ps aux

      - name: Mostrar logs del servidor
        run: cat server.log

      - name: Verificar puertos en uso
        run: netstat -tuln | grep 5500 || true

      - name: Esperar a que el servidor esté listo
        run: npx wait-on http://localhost:5500

      - name: Ejecutar tests Playwright
        run: npx playwright test

      - name: Subir resultados de test si fallan
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report 