name: CI Playwright

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Instalar navegadores Playwright
        run: npx playwright install --with-deps

      - name: Levantar servidor local
        run: npx http-server -p 5500 &

      - name: Esperar a que el servidor esté listo
        run: npx wait-on http://localhost:5500

      - name: Ejecutar tests Playwright
        run: npx playwright test

      - name: Subir resultados de test si fallan
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report 